(cl:defpackage roscopter-srv
  (:use )
  (:export
   "APMCOMMAND"
   "<APMCOMMAND-REQUEST>"
   "APMCOMMAND-REQUEST"
   "<APMCOMMAND-RESPONSE>"
   "APMCOMMAND-RESPONSE"
   "SENDWAYPOINT"
   "<SENDWAYPOINT-REQUEST>"
   "SENDWAYPOINT-REQUEST"
   "<SENDWAYPOINT-RESPONSE>"
   "SENDWAYPOINT-RESPONSE"
   "XBEECOMMAND"
   "<XBEECOMMAND-REQUEST>"
   "XBEECOMMAND-REQUEST"
   "<XBEECOMMAND-RESPONSE>"
   "XBEECOMMAND-RESPONSE"
   "SENDWAYPOINTLIST"
   "<SENDWAYPOINTLIST-REQUEST>"
   "SENDWAYPOINTLIST-REQUEST"
   "<SENDWAYPOINTLIST-RESPONSE>"
   "SENDWAYPOINTLIST-RESPONSE"
  ))

