/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/jay/ros/src/roscopter/srv/SendWaypoint.srv
 *
 */


#ifndef ROSCOPTER_MESSAGE_SENDWAYPOINTREQUEST_H
#define ROSCOPTER_MESSAGE_SENDWAYPOINTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <roscopter/Waypoint.h>

namespace roscopter
{
template <class ContainerAllocator>
struct SendWaypointRequest_
{
  typedef SendWaypointRequest_<ContainerAllocator> Type;

  SendWaypointRequest_()
    : waypoint()  {
    }
  SendWaypointRequest_(const ContainerAllocator& _alloc)
    : waypoint(_alloc)  {
    }



   typedef  ::roscopter::Waypoint_<ContainerAllocator>  _waypoint_type;
  _waypoint_type waypoint;




  typedef boost::shared_ptr< ::roscopter::SendWaypointRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roscopter::SendWaypointRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SendWaypointRequest_

typedef ::roscopter::SendWaypointRequest_<std::allocator<void> > SendWaypointRequest;

typedef boost::shared_ptr< ::roscopter::SendWaypointRequest > SendWaypointRequestPtr;
typedef boost::shared_ptr< ::roscopter::SendWaypointRequest const> SendWaypointRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roscopter::SendWaypointRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roscopter::SendWaypointRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roscopter

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'roscopter': ['/home/jay/ros/src/roscopter/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roscopter::SendWaypointRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roscopter::SendWaypointRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roscopter::SendWaypointRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roscopter::SendWaypointRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roscopter::SendWaypointRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roscopter::SendWaypointRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roscopter::SendWaypointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d5e91ece00199d55c16efd2c9c4801c9";
  }

  static const char* value(const ::roscopter::SendWaypointRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd5e91ece00199d55ULL;
  static const uint64_t static_value2 = 0xc16efd2c9c4801c9ULL;
};

template<class ContainerAllocator>
struct DataType< ::roscopter::SendWaypointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roscopter/SendWaypointRequest";
  }

  static const char* value(const ::roscopter::SendWaypointRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roscopter::SendWaypointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Waypoint waypoint\n\
\n\
================================================================================\n\
MSG: roscopter/Waypoint\n\
# latitude and longitude given in decimal degrees (* 10^7)\n\
int32 latitude\n\
int32 longitude\n\
\n\
# height in mm\n\
int32 altitude\n\
\n\
# posAcc given in mm\n\
uint16 pos_acc\n\
\n\
# max speed to travel to waypoint in % of 100\n\
uint8 speed_to\n\
\n\
# time to stay at waypoint in ms\n\
uint16 hold_time\n\
\n\
# yawFrom angle given in degrees (* 1000)\n\
int32 yaw_from\n\
\n\
# camera pan and tilt angles during waypoint travel given in degrees (* 1000)\n\
int32 pan_angle\n\
int32 tilt_angle\n\
\n\
# Type of Waypoint\n\
uint8 waypoint_type\n\
\n\
uint8 TYPE_NAV = 1\n\
uint8 TYPE_CONDITION_YAW = 2\n\
uint8 TYPE_CONDITION_CHANGE_ALT = 3\n\
uint8 TYPE_TAKEOFF = 4\n\
";
  }

  static const char* value(const ::roscopter::SendWaypointRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roscopter::SendWaypointRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.waypoint);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct SendWaypointRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roscopter::SendWaypointRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roscopter::SendWaypointRequest_<ContainerAllocator>& v)
  {
    s << indent << "waypoint: ";
    s << std::endl;
    Printer< ::roscopter::Waypoint_<ContainerAllocator> >::stream(s, indent + "  ", v.waypoint);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSCOPTER_MESSAGE_SENDWAYPOINTREQUEST_H
