/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/jay/ros/src/roscopter/srv/XBEECommand.srv
 *
 */


#ifndef ROSCOPTER_MESSAGE_XBEECOMMANDREQUEST_H
#define ROSCOPTER_MESSAGE_XBEECOMMANDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roscopter
{
template <class ContainerAllocator>
struct XBEECommandRequest_
{
  typedef XBEECommandRequest_<ContainerAllocator> Type;

  XBEECommandRequest_()
    : command(0)  {
    }
  XBEECommandRequest_(const ContainerAllocator& _alloc)
    : command(0)  {
    }



   typedef int8_t _command_type;
  _command_type command;


    enum { STARTMISSION = 1 };
     enum { MISSIONFINISHED = 2 };
     enum { FAILSAFE = 3 };
 

  typedef boost::shared_ptr< ::roscopter::XBEECommandRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roscopter::XBEECommandRequest_<ContainerAllocator> const> ConstPtr;

}; // struct XBEECommandRequest_

typedef ::roscopter::XBEECommandRequest_<std::allocator<void> > XBEECommandRequest;

typedef boost::shared_ptr< ::roscopter::XBEECommandRequest > XBEECommandRequestPtr;
typedef boost::shared_ptr< ::roscopter::XBEECommandRequest const> XBEECommandRequestConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roscopter::XBEECommandRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roscopter::XBEECommandRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roscopter

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'roscopter': ['/home/jay/ros/src/roscopter/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roscopter::XBEECommandRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roscopter::XBEECommandRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roscopter::XBEECommandRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roscopter::XBEECommandRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roscopter::XBEECommandRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roscopter::XBEECommandRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roscopter::XBEECommandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4092736087ba4328fa7dc96a85fda7a6";
  }

  static const char* value(const ::roscopter::XBEECommandRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4092736087ba4328ULL;
  static const uint64_t static_value2 = 0xfa7dc96a85fda7a6ULL;
};

template<class ContainerAllocator>
struct DataType< ::roscopter::XBEECommandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roscopter/XBEECommandRequest";
  }

  static const char* value(const ::roscopter::XBEECommandRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roscopter::XBEECommandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 command\n\
int8 STARTMISSION = 1\n\
int8 MISSIONFINISHED = 2\n\
int8 FAILSAFE = 3\n\
";
  }

  static const char* value(const ::roscopter::XBEECommandRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roscopter::XBEECommandRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct XBEECommandRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roscopter::XBEECommandRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roscopter::XBEECommandRequest_<ContainerAllocator>& v)
  {
    s << indent << "command: ";
    Printer<int8_t>::stream(s, indent + "  ", v.command);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSCOPTER_MESSAGE_XBEECOMMANDREQUEST_H
